build_from:
  amd64: ghcr.io/home-assistant/amd64-base:latest
labels:
  org.opencontainers.image.title: "Home Service Bus Add-on: H.S.B"
  org.opencontainers.image.description: "'Home Service Bus' Add-on for HA."
  org.opencontainers.image.source: "https://github.com/rockyhopper/hassio-repository"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
# hsb_version: dev-latest-SNAPSHOT
# Use (Build #? of Nov 11th, 2024 or later)

