name: "H.S.B (Development version)"
version: dev-latest
slug: hsb_dev
description: "Development version of 'Home Service Bus' Add-on for HA"
url: "https://github.com/rockyhopper/smarthome/tree/feature/hsb"
arch:
  - amd64
  - armv7
init: false
map:
  - share:rw
options:
  message: "Hello world HSB. (SRC).."
  gretings.suffix: "'Default Suffix from HA (built by github)"
  mqtt.username: $(bashio::services mqtt "username")
  mqtt.password: $(bashio::services mqtt "password")
  mqtt.host-url: $(bashio::services mqtt "host")
  logging.level.root: ["debug", "info", "warn", "error"]
schema:
  message: "str?"
  gretings.suffix: "str?"
  mqtt.username: "str"
  mqtt.password: "password?"
  mqtt.host-url: "str"
  ha.protocol: "str"
  ha.host: "host"
  ha.port: "port?"
  ha.bearer: "bearer?"
  logging.level.root: ["str?"]
image: "rockyhopper/{arch}-ha-addon-hsb_dev"
apparmor: false
ingress: true
ingress_port: 8082
ingress_stream: true
homeassistant_api: true
ports:
  8082/tcp: 8082
ports_description:
  8080/tcp: HSB Web Interface

