build_from:
  amd64: ghcr.io/home-assistant/amd64-base:latest
  armv7: ghcr.io/home-assistant/armv7-base:latest
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: W.E.S (Web Energie Superviseur)"
  org.opencontainers.image.description: "'Web Energie Superviseur' Add-on for HA."
  org.opencontainers.image.source: "https://github.com/rockyhopper/hassio-repository"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
# wes2mqtt_version: dev-latest-SNAPSHOT
# Use (Build #18)

