name: "W.E.S (Development version)"
version: 0.9.2-beta
slug: wes_dev
description: "Development version of 'Web Energie Superviseur' Add-on for HA"
url: "https://github.com/rockyhopper/hassio-repository/tree/main/wes_dev"
arch:
  - amd64
  - armv7
init: false
map:
  - share:rw
options:
  message: "Hello world. (SRC).."
  gretings.suffix: "'Default Suffix from HA (built by github)"
  mqtt.username: $(bashio::services mqtt "username")
  mqtt.password: $(bashio::services mqtt "password")
  mqtt.host-url: $(bashio::services mqtt "host")
  wes.ipAddress: null
  wes.macAddress: null
  wes.tcpPort: 1500
  wes.httpUser: admin
  wes.httpPass: wes
  wes.ftpUser: adminftp
  wes.ftpPass: wesftp
  wes.discoveryInterfaceIPs: 192.168.1.1/24
  logging.level.root: ["debug", "info", "warn", "error"]
schema:
  message: "str?"
  gretings.suffix: "str?"
  mqtt.username: "str"
  mqtt.password: "password?"
  mqtt.host-url: "str"
  wes.ipAddress: "str?"
  wes.macAddress: "str?"
  wes.tcpPort: "port?"
  wes.httpUser: "str?"
  wes.httpPass: "password?"
  wes.ftpUser: "str?"
  wes.ftpPass: "password?"
  wes.discoveryInterfaceIPs: "str?"
  logging.level.root: ["str?"]
image: "rockyhopper/{arch}-ha-addon-wes_dev"
apparmor: false
ingress: true
ingress_port: 8081
ingress_stream: true
ports:
  8081/tcp: 8081
ports_description:
  8080/tcp: WES to Mqtt Web Interface
